lan:
  test:
    oauth:
      audience: ${lan.test.oauth.client}
      authorization-url: ${lan.test.oauth.authorization-url}
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${lan.test.oauth.issuer-uri}
          jwk-set-uri: ${lan.test.oauth.jwk-set-uri}
springdoc:
  show-actuator: true
  swagger-ui:
    oauth:
      client-id: ${lan.test.oauth.client}
      scopes: ${lan.test.oauth.scopes}